export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
  NON_BINARY = "NON-BINARY",
  ANY = "ANY",
  INTERSEX = "INTERSEX",
  TRANS_FTM = "TRANS-FTM",
  TRANS_MTF = "TRANS-MTF",
  TRANS_ANY = "TRANS-ANY",
  GENDERFLUID = "GENDERFLUID",
}
