export enum Species {
  HUMAN = "HUMAN",
  ELF = "ELF",
  VAMPIRE = "VAMPIRE",
  DEMON = "DEMON",
  ANDROID = "ANDROID",
  HUMANOID_ANIMAL = "HUMANOID_ANIMAL",
  FAIRY = "FAIRY",
  WITCH = "WITCH",
  WIZARD = "WIZARD",
  ANGEL = "ANGEL",
  DEITY = "DEITY",
  HALF = "HALF",
}

export enum HalfSpecies {
  HALF_ELF = "HALF_ELF",
  HALF_VAMPIRE = "HALF_VAMPIRE",
  HALF_DEMON = "HALF_DEMON",
  HALF_HUMAN = "HALF_HUMAN",
  HALF_ANDROID = "HALF_ANDROID",
  HALF_HUMANOID_ANIMAL = "HALF_HUMANOID_ANIMAL",
  HALF_FAIRY = "HALF_FAIRY",
  HALF_WITCH = "HALF_WITCH",
  HALF_WIZARD = "HALF_WIZARD",
  HALF_ANGEL = "HALF_ANGEL",
  HALF_DEITY = "HALF_DEITY",
}
